### PR TITLE
Remove experiment code

### PR DESCRIPTION
**Pull request by SlayterDev**
**Reviewer:** @sammacbeth @kdzwinel @dharb 

## Description:

Remove cookie experiment code

## Steps to test this PR:
1. Should block cookies on https://privacy-test-pages.glitch.me/privacy-protections/storage-blocking/

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Review by sammacbeth — COMMENTED** [review]
I'm wondering if a simpler approach would be to just return `true` from `blockingExperimentActive`, which would then make it easier to toggle this feature, for example for debugging, or feature flags.

**Comment by SlayterDev** [comment]
cc @jonathanKingston

**Comment by jonathanKingston** [comment]
I agree with Sam although it's not related to the content script changes. I'd rename the function if we are keeping it though.

**Comment by jonathanKingston** [comment]
> > I agree with Sam although it's not related to the content script changes. I'd rename the function if we are keeping it though.
> 
> @jonathanKingston would it be easier for me to change the function to return `true` and let you change the name?

I just mean rename to something meaning it's not an experiment like `isThirdPartyCookieEnabled` or whatever. I can raise an issue if you like.

**Comment by SlayterDev** [comment]
> > > I agree with Sam although it's not related to the content script changes. I'd rename the function if we are keeping it though.
> 
> > 
> 
> > @jonathanKingston would it be easier for me to change the function to return `true` and let you change the name?
> 
> 
> 
> I just mean rename to something meaning it's not an experiment like `isThirdPartyCookieEnabled` or whatever. I can raise an issue if you like.

No worries. I'll knock this out first thing in the morning (unless you need it sooner?)

**Comment by jonathanKingston** [comment]
Nope no rush at all, doesn't relate to any current work I'm doing :) thanks

**Comment by SlayterDev** [comment]
It's easier to destroy this branch and start again (easy/lazy take your pick) so I'll be doing that.

**Pull request closed without merging**
