### PR TITLE
Re-enable ToS;DR Script and update latest data

### LINKED ISSUE #482: tosdr.json not getting updated?
Hi!

First of all, thanks again for all your great work on this extension, it's really helping user stay informed.

I have a question - it seems https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/develop/shared/data/tosdr.json was last updated 13 months ago. But as you can see from https://github.com/tosdr/tosdr.org/commits/master/index/services.json 
we do update https://tosdr.org/index/services.json more regularly than that, so I think maybe our changes there are not getting picked up by your build script (anymore). Are you still running https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/master/scripts/tosdr.js as part of your release process?

### PR DESCRIPTION
**Pull request by JustinBack**
**Reviewer:**

## Description:
I have fixed the tosdr.js script to reflect the current data set uri and skip if it failed to get privacy data.
This PR also includes the latest dataset from tosdr.org where as the current state in master is from 2018.
I have also re-enabled the execution of the script in the gruntfile to get latest datasets on build.

This PR is more comprehensive than #380 even though the PR by @michielbdejong has essentially fixed the issue.

Closes #482 
Closes https://github.com/duckduckgo/Android/issues/973

## Steps to test this PR:
Simply compile the extension via make, execute the gruntfile or run the script manually.
-->

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by michielbdejong** [comment]
@JustinBack thanks for picking this up!

Hm, the build is failing on this PR but probably not due to anything inside it, many other branches are also failng, see https://travis-ci.org/github/duckduckgo/duckduckgo-privacy-extension/branches

**Comment by Super-Cow-Pig173** [comment]
Good catch

**Comment by Super-Cow-Pig173** [comment]
Good catch

**Review by Chew — APPROVED** [review]
Hope to see this implemented! This is a great service and I would love to see it updated

**Comment by ruurtjan** [comment]
Hey @jonathanKingston @sammacbeth, is anything blocking this merge? Would be nice to have TOS;DR working again :)

**Comment by JustinBack** [comment]
I have updated the scripts again for our latest API standards. The only disadvantage now is that you'd need an API Key generated by us to get all service data as you hit the hourly rate limit pretty quickly with over 2000 services.


(We need to pull each service one by one to get points data)



This API Key can be entered using the environment variable TOSDR_APIKEY


Currently a lot of case data is saved by caching requests to the case/v1 endpoint, sadly this cannot be done at the service endpoint.

**Comment by JustinBack** [comment]
Also not entirely sure if its wise to hardcode Grades into unit tests?



Especially since Google, Reddit, twitter, facebook have a different rating (All E) on ToS;DR. independent is not rated at all, so all PR checks fail

**Comment by JustinBack** [comment]
The way I currently handle it is by having a "warning" system if the requests are not enough to make a complete file or abort if no file can be created.

**Comment by sammacbeth** [comment]
@ruurtjan We are currently evaluating this feature internally, which is why we haven't updated it recently. We'll evaluate this PR once we've made a decision.

**Comment by saturnonearth** [comment]
> @ruurtjan We are currently evaluating this feature internally, which is why we haven't updated it recently. We'll evaluate this PR once we've made a decision.

Any update on this?

**Comment by iamashley0** [comment]
still no updates

**Comment by jonathanKingston** [comment]
No real change here, it's on our timeline to update other higher priority work has taken precedence but we're expecting an update in the next few months here.

**Comment by JustinBack** [comment]
> No real change here, it's on our timeline to update; other higher priority work has taken precedence but we're expecting an update in the next few months here.

So, with the removal of ToS;DR: Is this PR stale?

**Comment by sammacbeth** [comment]
As the new dashboard design doesn't use ToS;DR, I think we can close this PR.

**Comment by JustinBack** [comment]
Thanks for the response, it would have been nice to get notified tho, or any info why/when this feature gets removed

**Pull request closed without merging**
