### PR TITLE
Fix layout of 'Learn more' link

### PR DESCRIPTION
**Pull request by imsoumya18**
This is a fix to Issue#1029

### CODE REVIEW

**Comment by sammacbeth** [comment]
Thanks for this PR! Testing locally, there seems to be a bit too much padding around the link in Chrome. Could to try and make the padding match the Fire button link?
Screenshot 2023-08-23 at 12 29 19

**Comment by imsoumya18** [comment]
Sure, I shall go through it

**Comment by imsoumya18** [comment]
@sammacbeth please review the 2nd PR I have created. I have fixed the padding

**Review by sammacbeth — APPROVED** [review]
Thank you for the patch! Looks good now.

**Pull request merged**
