### PR TITLE
fix: re-instate setList message

### PR DESCRIPTION
**Pull request by shakyShane**
**Reviewer:** @jonathanKingston 

## Description:

`setList` was removed by mistake - it's used on the options page.

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Review by jonathanKingston — APPROVED** [review]

**Review by fund-raiser — COMMENTED** [review]
Hi

**Review by fund-raiser — COMMENTED** [review]
Hi[CTB](24)

**Review by fund-raiser — COMMENTED** [review]
Hi[CTB](24)

**Review by fund-raiser — COMMENTED** [review]
Hi[CTB](24)

**Pull request merged**
