### PR TITLE
Start using the v4 block list again

### PR DESCRIPTION
**Pull request by kzar**
Now that the rule matching code in privacy-grade has been updated to
properly ignore unsupported rule actions, it should be safe to switch
back to the v4 block list again. That is necessary to get Click to
Load working for MV3 builds again, and is the next step towards
removing the legacy social_ctp_configuration.json[1] configuration
file.

Note: We also needed to fix the Click to Load YouTube test
      configuration, that was missing the surrogate script entry. It
      turned out that this was working by accident using the v4 block
      list actions in the test block list file.

1 - https://staticcdn.duckduckgo.com/useragents/social_ctp_configuration.json

**Reviewer:** @jdorweiler 
**CC:** @ladamski 

## Steps to test this PR:
MV2:
1. Check that Facebook Click to Load works correctly ([see the test page](https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/)).
2. Check that videos load as normal [on the YouTube test page](https://privacy-test-pages.glitch.me/privacy-protections/youtube-click-to-load/).

MV3:
1. Check that Facebook Click to Load works correctly ([see the test page](https://privacy-test-pages.glitch.me/privacy-protections/click-to-load/)). Especially important is to check that requests are being blocked (not only that the placeholders are being shown.)
2. It's expected that videos are blocked incorrectly, with no placeholder shown [on the YouTube test page](https://privacy-test-pages.glitch.me/privacy-protections/youtube-click-to-load/). I will be fixing that next.

## Automated tests:
- [ ] Unit tests
- [x] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by ladamski** [comment]
`Test YouTube Click To Load CTL: YouTube interacting with iframe API` is failing for me locally so there's something a bit broken I suspect (running `test-int` so MV2)

**Comment by kzar** [comment]
> Also Youtube doesn't load in MV3 as its blocked (since youtube CTL is not yet ready). But since Youtube action is not defined/enabled in [duckduckgo/privacy-configuration#603](https://github.com/duckduckgo/privacy-configuration/pull/603), we should ensure that MV3 also abides by the config?

Yea, that's expected (see testing instructions). It will be next on my list to fix, after we land this.

**Comment by ladamski** [comment]
> > Also Youtube doesn't load in MV3 as its blocked (since youtube CTL is not yet ready). But since Youtube action is not defined/enabled in [duckduckgo/privacy-configuration#603](https://github.com/duckduckgo/privacy-configuration/pull/603), we should ensure that MV3 also abides by the config?
> 
> Yea, that's expected (see testing instructions). It will be next on my list to fix, after we land this.

Yes but as I said, since the action is not enabled we should not be blocking those in MV3 either?

**Comment by kzar** [comment]
> > > Also Youtube doesn't load in MV3 as its blocked (since youtube CTL is not yet ready). But since Youtube action is not defined/enabled in [duckduckgo/privacy-configuration#603](https://github.com/duckduckgo/privacy-configuration/pull/603), we should ensure that MV3 also abides by the config?
> > 
> > 
> > Yea, that's expected (see testing instructions). It will be next on my list to fix, after we land this.
> 
> Yes but as I said, since the action is not enabled we should not be blocking those in MV3 either? To clarify, do you mean you'll fix youtube next or fix skipping disabled actions for MV3? :)

I meant I will be fixing MV3 Click to Load next, so that it's only active when it should be. Fixing YouTube CTL is out of scope for this project.

**Review by jdorweiler — APPROVED** [review]

**Pull request merged**
