### PR TITLE
Check broken site list for cookies

### PR DESCRIPTION
**Pull request by SlayterDev**
**Reviewer:** @sammacbeth 

## Description:

Check if a site is broken before blocking 3p cookies

## Steps to test this PR:
1. Visit a site on the temp allow list
2. Verify 3p cookies are not blocked

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by jonathanKingston** [comment]
Could we pass `site` to `blockTrackingCookies` and use that for all three statements? Moving the `!site.whitelisted && !site.isBroken` to the return value of that method.

**Comment by SlayterDev** [comment]
> Could we pass `site` to `blockTrackingCookies` and use that for all three statements? Moving the `!site.whitelisted && !site.isBroken` to the return value of that method.

I'm inclined to say no just because `blockTrackingCookies` is meant to be a toggle if that feature is enabled or not.

**Comment by jonathanKingston** [comment]
Ah yeah it's supposes to be the same as:
```
export function isFeatureBroken (args, feature) {
    return args.site.brokenFeatures.includes(feature)
}
```

Can we add the blockTrackingCookies to the other two checks if they're applicable?

**Comment by SlayterDev** [comment]
That's already being done. Just earlier in the flow for those cases.

**Review by jonathanKingston — APPROVED** [review]

**Pull request merged**
