### PR TITLE
Fix canvas issues

### PR DESCRIPTION
**Pull request by jonathanKingston**
**Reviewer:** @Charlie-belmer 

## Description:

- First pixel data returning '0' created div by 0 issues which was pretty common
- The image data wasn't being used correctly, but stringifying the key full length was really expensive with the crypto algo
  - We could consider some method similar to nextRandom to return a short determinisitic string
- Verifying I'm hitting all the channels (I think I am anyway)
- TODO the same response appears to be returned toDataURL across origins.

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Review by Charlie-belmer — COMMENTED** [review]
Looks good to me. I suggest that we add some comment documentation. It isn't obvious to me why sumData is needed. You mentioned this is WIP, so let me know when you want a closer look!

**Comment by jonathanKingston** [comment]
> Looks good to me. I suggest that we add some comment documentation. It isn't obvious to me why sumData is needed. You mentioned this is WIP, so let me know when you want a closer look!

The main reason it's needed is due to the speed of using the entire data string. Using the privacy page example there was very obvious slow down in even drawing to the canvas. Previously this was inconsistent across browsers with Firefox using something like "[Object object]" as the key.
This is something I want to tear apart and make unit tests of when we have the ability to so this doesn't happen.

**Comment by jonathanKingston** [comment]
The main rationale to using something more pseudo random than just summing the pixel data together, is to prevent collisions which might be exposable in the fingerprint and timing attacks would be less predictable too. But the counter case it comes at more cost. (however nothing on the cost of using a 30k byte key)

**Review by Charlie-belmer — APPROVED** [review]
Looks good to me, thanks for doing this!

**Pull request merged**
