### PR TITLE
Add all locales for options view

### PR DESCRIPTION
**Pull request by ladamski**
**Reviewer:**

## Description:
https://app.asana.com/0/1202416379154655/1202467416438011
Adds strings for options view, for all supported locales.  
Also cleans up i18next init code to follow the pattern in the dashboard.

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Review by shakyShane — APPROVED** [review]
LGTM

**Comment by ladamski** [comment]
@shakyShane hmm it occurred to me that if I were to merge this into `develop` as is, it would start localizing the options page without anything else being localized.  I could merge this into your working `shane/pd` branch instead, once you rebase it be current with `develop`?

**Comment by shakyShane** [comment]
@ladamski Ahh yeah that's a good point. I'm more than happy for you to keep this branch open, and I'll merge it into mine today/tomorrow as a I prepare my own PR.

**Comment by ladamski** [comment]
@shakyShane just checking in, to make sure we don't forget about this :)

**Comment by shakyShane** [comment]
Thanks @ladamski - yeah I'm starting to think this work should just be merged into my branch now (which I think you originally suggested).

Just to be 100% clear, this work doesn't make sense until the newly-designed dashboard lands, is that correct?

**Comment by ladamski** [comment]
@shakyShane yeah might as well merge it now, though the localization wasn't targeted at the new design per se.  Either way it should land first so the new design can be localized from the get-go.

**Pull request merged**
