### PR TITLE
Update ddg2dnr dependency

### PR DESCRIPTION
**Pull request by kzar**
**Reviewer:** @ladamski 
**CC:** @jdorweiler 
**Depends on:** 

## Description:
Update ddg2dnr to include CTL and tracker parameter protection changes.

### CODE REVIEW

**Review by ladamski — APPROVED** [review]
👍 briefly tested with the develop mv2/mv3 builds and seems to work as expected

**Comment by ladamski** [comment]
Actually ran into an unexpected issue.  For the MV3 CTL branch, unit tests pass with the corresponding ddg2dnr branch that was merged, but fail with the 0.2.6 ddg2dnr release.

Or to put it another way, for https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/1527

`npm i -S github:duckduckgo/ddg2dnr#la/support-click-to-load && npm test` = PASS

`npm i -S github:duckduckgo/ddg2dnr#0.2.6 && npm test` = FAIL with **Error: Missing isRegexSupported function.**

Chrome Headless 108.0.5351.0 (Mac OS 10.15.7) declarativeNetRequest getMatchDetails FAILED
	Error: Missing isRegexSupported function.
	    at generateExtensionConfigurationRuleset (node_modules/@duckduckgo/ddg2dnr/lib/extensionConfiguration.js:36:1)
	    at shared/js/background/declarative-net-request.js:144:56
	    at <Jasmine>
	    at asyncGeneratorStep (shared/js/background/declarative-net-request.js:19:48)
	    at _next (shared/js/background/declarative-net-request.js:19:48)
Chrome Headless 108.0.5351.0 (Mac OS 10.15.7) declarativeNetRequest Config ruleset updates FAILED
	Error: Missing isRegexSupported function.
	    at generateExtensionConfigurationRuleset (node_modules/@duckduckgo/ddg2dnr/lib/extensionConfiguration.js:36:1)
	    at shared/js/background/declarative-net-request.js:144:56
	    at <Jasmine>
	    at asyncGeneratorStep (shared/js/background/declarative-net-request.js:19:48)
	    at _next (shared/js/background/declarative-net-request.js:19:48)

I also saw this (inconsistently) in Chrome while testing with that latter build

**Comment by kzar** [comment]
> Actually ran into an unexpected issue. For the MV3 CTL branch, unit tests pass with the corresponding ddg2dnr branch that was merged, but fail with the 0.2.6 ddg2dnr release.

The tests are passing for this change though. I figure if the tests are failing for your WIP Chrome MV3 Click to Load branch, perhaps it's related to your changes in that branch.

**Review by ladamski — APPROVED** [review]
Yep it was fixed with a rebase

**Pull request merged**
