### PR TITLE
Protect against some anti-fingerprint bypasses.

### PR DESCRIPTION
**Pull request by Charlie-belmer**
Improve anti-fingerprinting scripts to prevent some bypasses.

### CODE REVIEW

**Comment by palant** [comment]
Yes, this seems to solve it. For reference, there is [a better way to solve this on Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts), something that I wasn’t aware of myself until recently. Sadly, Chromium doesn’t have such functionality, there running code in a hostile environment is unavoidable.

**Comment by palant** [comment]
There are more places in this script affected for the same issue however. For example, `navigator.getBattery()` is being overwritten instead of `Navigator.prototype.getBattery()`. The resulting value is also a mess – not a `BatteryManager` instance and nothing like it either.

There are calls to `setWindowPropertyValue()` which all suffer from the same issue as well and more…

**Comment by Charlie-belmer** [comment]
Thanks @palant,

There's way more to update here, as you mention. I'll be taking a closer look in the new year.

**Comment by Charlie-belmer** [comment]
Thanks for all the help here - I think I addressed all your comments, and it's definitely looking way better.

**Review by dharb — APPROVED** [review]
Looks great, thanks @Charlie-belmer for making these changes. And hat-tip to @palant for the help identifying these issues, we really appreciate it.

**Pull request merged**
